FROM node:22-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./
RUN npm install

# Copy frontend source
COPY . .

# Build frontend
RUN npm run build

# Use Node to serve the build
EXPOSE 5173

CMD ["npm", "run", "preview"]
